# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

glmPR <- function(X, y, lambda = 0.5, threads = 4L) {
    .Call('glmPR_glmPR', PACKAGE = 'glmPR', X, y, lambda, threads)
}

